### ISSUE TITLE
`$GITHUB_STEP_SUMMARY` isn't documented

### ISSUE THREAD

**Issue by jsoref** [nektos/act-docs#18]
https://github.com/nektos/act/pull/1607 added some support for `$GITHUB_STEP_SUMMARY`

There is no documentation https://nektosact.com/?search=github_step_summary

Note that you can no longer use `--env GITHUB_STEP_SUMMARY=/dev/stdout` -- that's fine, although it'd be nice if there was a warning (this is out of scope).

The best I've found to access step summaries is:
```sh
act -r
while true; do
  act_docker_pid=$(docker ps|perl -ne 'next unless s{\s.*"tail -f /dev/null".*act-.*}{};print'|tail -1)
  if [ -z "$act_docker_pid" ]; then
    break
  fi
  echo "$(docker ps|grep ^$act_docker_pid)::"
  docker exec $act_docker_pid cat /var/run/act/workflow/SUMMARY.md
  echo
  docker rm -f $act_docker_pid > /dev/null
done
```

`act -r` means that the container is kept around
`GITHUB_STEP_SUMMARY` is generally defined as `/var/run/act/workflow/SUMMARY.md`

Note that each job is run in its own docker container so the files are independent.

(This isn't remotely ideal, but some documentation is better than nothing.)

---

It also should note that content written to `$GITHUB_STEP_SUMMARY` will be destroyed at the beginning of the next step, so anyone running a multistep workflow in ACT should *not* rely on it as the output from any step other than the last will not be accessible.

https://github.com/nektos/act/issues/2273

**Comment by stephanschielke** [comment]
Thanks for your research on this. This workaround helped me.

It looks like the path to `SUMMARY.md` is hardcoded [here](https://github.com/nektos/act/blob/master/pkg/runner/step.go#L122).

So are all the other files:
```
docker exec <running_act_container_id> ls -al /var/run/act/workflow
...
-rw-rw-rw- 1 root root    0 Jan  1  1970 SUMMARY.md
-rw-rw-rw- 1 root root    0 Jan  1  1970 envs.txt
-rw-r--r-- 1 root root    2 Jan  1  1970 event.json
-rw-rw-rw- 1 root root    0 Jan  1  1970 outputcmd.txt
-rw-rw-rw- 1 root root    0 Jan  1  1970 pathcmd.txt
-rw-rw-rw- 1 root root    0 Jan  1  1970 statecmd.txt
```

Also, there seems to be some very funky stuff going on with the `GITHUB_STEP_SUMMARY` env vars [here](https://github.com/nektos/act/blob/bda491e406db6c85865498ced18764bc00491a5e/pkg/runner/hashfiles/index.js#L772)
coming from [here](https://github.com/nektos/act/pull/1940)
but actually stemming from another repo and codebase [here](https://github.com/actions/runner/blame/main/src/Misc/layoutbin/hashFiles/index.js)

The only real solution IMHO is a dedicated feature as outlined (by you) [here](https://github.com/nektos/act/issues/2273#issuecomment-2041295011)

**Comment by ChristopherHX** [comment]
That this feature is absent is actually documented here: https://nektosact.com/not_supported.html#planned, but not using the env variable as name so search after that one has no result.
